# Generated by Django 2.2 on 2021-05-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210522_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user_name',
            new_name='username',
        ),
    ]
